apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloud-eln
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloud-eln

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: cloud-eln

  template:
    metadata:
      labels:
        app: cloud-eln

    spec:
      containers:
        - name: cloud-eln
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
            - secretRef:
                name: {{ .Values.secret.name }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          volumeMounts:
            - name: cloud-eln-storage
              mountPath: /data

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

      volumes:
        - name: cloud-eln-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolume.claimName }}