apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: cloud-eln-ingress
  namespace: cloud-eln

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - host: {{ .Values.ingress.host }}

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: cloud-eln-service

                port:
                  number: {{ .Values.service.port }}