apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.persistentVolume.claimName }}
  namespace: cloud-eln

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi