apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  SECRET_KEY: "super-secret-key-123"
  DATABASE_PASSWORD: "postgres-password"