apiVersion: v1
kind: Service

metadata:
  name: cloud-eln-service
  namespace: {{ .Release.Namespace }}

spec:
  type: NodePort

  selector:
    app: cloud-eln

  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000